! http://clarionedge.com, http://fushnisoft.com
! Licensed under the MIT license: https://github.com/fushnisoft/ClarionMetroWizard/blob/master/LICENSE.txt 

_ce_BaseWindowComponent_  EQUATE(1)
  include('ABWINDOW.INC'),ONCE
!--------------------------------------------------------------------------------
!Class ce_BaseWindowComponent
!
!--------------------------------------------------------------------------------
ce_BaseWindowComponent Class(),Implements(WindowComponent),Type,Module('ce_BaseWindowComponent.Clw'),LINK('ce_BaseWindowComponent.Clw',1)
! Properties
! Methods
                     END ! Class Definition
!_EndOfInclude_
